hydra:
  output_subdir: null  
  run:
    dir: .

defaults:
  - process: process1
  - model: model1
  - _self_

sim_name: 'rd_sim_2d'
label: null

################################################
# Environment Setting Hyper-parameters.  #
################################################
seed: 123
verbose: true
jax_enable_x64: true
xla_preallocate: false


# Reaction-diffusion parameters
warm_up: 200
alpha: 0.01
beta: 1.0
gamma: 0.05
widthx: 6.4
widthy: 6.4


# Solver Parameters 
domain_size: [1, 1]
nx: 128
ny: 32
dt: 0.01

#['scalar_grid', extrapolation_x:(type or bound), extrapolation_y:(type or bound)]
particle_extrapolation: 'BOUNDARY'
    
#['staggered_grid', extrapolation_x:(type or bound), extrapolation_y:(type or bound)]
velocity_extrapolation: 'ZERO'

# Fluid characteristics
NU: 0.01 #(kinematic viscosity)

# External force
# enable_gravity: false
force_extrapolation: 'ZERO'

# Fluctuation Generator Parameters (Noise)
seed: 1
smoothness: 1.0
scale: 0.4
force_smoothness: 3.0
force_scale: 0.15

#params for IncompressibleFlow(Physics)
n_steps: 100000
DT : 0.00005
frame_int: 100

n_batch: 1

# Visualisation
# save_images: false
# save_gif: false
save_h5: true
profile: false  # Run performance profiling
upload: false   # upload to DARUS - requires key

backend: 'jax'
device: 'GPU'
jit: true


data:
  raw: data/raw/sample.csv
  processed: data/processed/processed.csv
  final: data/final/final.csv