# @package _global_

# specify here default sim configuration
defaults:
  - _self_

  - mode: default.yaml

# path to original working directory
# hydra hijacks working directory by changing it to the current log directory,
# so it's useful to have this path as a special variable
# https://hydra.cc/docs/next/tutorials/basic/running_your_app/working_directory
work_dir: ${hydra:runtime.cwd}

# path to folder with data
data_dir: data
upload: false

output_path: 2D_diff-react_NA_NA

# name of the run, accessed by loggers
name: react_diff

ks:
  nu: 1
  c: 1.6
  T: 400
  dt: .1
  L: 128
  nx: 1024
  r: 4
  init_scale: 1.
  BC: Dirichlet-Neumann

react_diff:
  alpha: 0.01
  beta: 1.0
  gamma: 0.05
  d: 2
  T: 5
  dt: 0.001
  Lx: 6.4
  nx: 256
  r: 2
  n: 2              # number of components

ns:
  nx: 128
  ny: 32
  Lx: 4.0
  Ly: 1.0
  Re: 100
  dim: 2
  T: 10
  dt: .01

sim:
  seed: 42
  case_num: 1       # number of simulations to perform
  warm_up: 200      # warm up step for simulation
  patience: 5       # patience for NaN simulation
  writeInterval: 2
  
plot:
  t_idx: 1.0        # Fraction of the final time step idx to be plotted
  dim: 2            # Spatial dimension
  channel_idx: 0    # Index of the variable to be plotted

train:
  stratify: False
  sgs: correction # filter, correction
  bins: 50
  subsample: 200
  mode: gaussian # regression, gaussian, generative
  linear: True # whether add a linear residue layer
  n_g: 1 # number of gaussian mixture components
  input: uxx # uglobal, u, ux, uxx, uxxxx
  lr: 0.01
  epochs: 2000
  epochs_ae: 200
  dagger_epochs: 10
  dagger_inner_epochs: 50
  batch_size: 1000000
  batch_size_ae: 500
  vae:
    latents: 128

test:
  model: alos
  solver: CN # CN, RK4

dataverse:
  lib_name: NA
  dataset_id: NA
  metadatablocks:
    citation:
      author:
        - name: Jiaxi Zhao
          affiliation: National University of Singapore
          identifier_scheme: ORCID
          identifier: 0009-0007-2110-6006
      description:
        - text: 2D diffusion-reaction dataset
          date: 2024
      contact:
        - name: Jiaxi Zhao
          affiliation: National University of Singapore
          email: jiaxi.zhao@u.nus.edu
      title: 2D diffusion-reaction dataset
      subject:
        - computer_and__information__science
        - physics
    process:
      processing_methods:
        - name: FVM
          description: Finite Volume Method is a spatial discretization method to calculate spatial derivative in a Partial Differential Equation. It integrates the fluxes at all discrete cell boundaries so that it ensures conservation.
          parameters: cell length, cell width
        - name: RK45
          description: Explicit Runge-Kutta method of order 5(4) is a time integration method to solve the temporal derivative in a Partial Differential Equation. It is an adaptive time integration scheme to ensure better accuracy and computation efficiency.
          parameters: time step size, total time, error tolerance
      method_parameters:
        - name: cell length
          symbol: dx
          unit: m
          value: 0.015625
        - name: cell width
          symbol: dy
          unit: m
          value: 0.015625
        - name: time step size
          symbol: dt
          unit: s
          value: 0.05
        - name: total time
          symbol: t
          unit: s
          value: 5
        - name: error tolerance
          symbol: \epsilon
          unit: "-"
          value: 1e-6
    engMeta: {}
    codeMeta: {}